### ISSUE TITLE
Non-root users?

### ISSUE THREAD

**Issue by davidjpeacock** [purpleidea/puppet-ssh#1]
Hey James,

I love the idea of this project, and pouring over your code it looks like you've made a great start.  :+1: 

That being said, I wonder if you'd be open to my suggesting support for non-root users?  In my puppet environments I prefer to setup per-user key-pairs, and then rely on sudo for privilege escalation.

Want some help?

Keep up the great work anyways!

**Comment by purpleidea** [comment]
On Wed, 2014-06-18 at 18:18 -0700, David Peacock wrote:

> Hey James,
> Hey,
> 
> I love the idea of this project, and pouring over your code it looks
> like you've made a great start.  :+1: 
> Thanks! One caveat that you've probably discovered, is that it's really
> a combination of all things "ssh", where technically it wouldn't have
> been bad if I split the ssh server and the client (file handling) stuff
> into different parts. In any case I decided to keep them together, even
> though they're not currently directly related :)
> 
> That being said, I wonder if you'd be open to my suggesting support
> for non-root users?
> I think I have at least one comment in my source about this type of
> thing... If it's not in the source it's in my head... It's a bit
> trickier than you might think to do because of:
> https://github.com/purpleidea/puppet-ssh/blob/master/lib/facter/ssh_keys.rb#L22

I don't know how to properly scale this yet, without some hacks that I'm
trying to avoid... But I'm open to doing it, although I'd prefer an
elegant solution to scaling it to N users.

>   In my puppet environments I prefer to setup per-user key-pairs, and
> then rely on sudo for privilege escalation.
> You'll have to provide more info on how you'd want to do the sudo parts,
> and which parts of the module you're thinking about...
> 
> Want some help?
> So yes, of course I'm happy to collaborate on this, although my free
> time varies based on my other projects. IOW, don't be offended if I
> don't respond right away, or alternatively, feel free to bug me a lot.
> 
> Keep up the great work anyways!
> Thank you for your comments!

**Comment by davidjpeacock** [comment]
Awesome - my time is choppy too but I'll try to make time - thanks so much for the opportunity.  There's a useful tool called pubkeyfs which is a FUSE filesystem for SSH public keys.  Bolting that in should be a good start in solving the problem you pointed to. :-)

https://github.com/kelseyhightower/pubkeyfs

When you get a minute to weigh this up, let me know your thoughts!

Cheers,
David
